version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://rohit:rohitgiftrove123@europe-west1-001.proxy.kinsta.app:30157/rohit-db?sslmode=disable
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_USER=rohit
      - POSTGRES_PASSWORD=rohitgiftrove123
      - POSTGRES_DB=rohit-db
      - POSTGRES_HOST=europe-west1-001.proxy.kinsta.app
      - POSTGRES_PORT=30157
      - PGSSLMODE=disable
      - PGAPPNAME=giftrove_app
    volumes:
      - uploads:/app/uploads
    command: >
      sh -c "while ! nc -z -w5 $POSTGRES_HOST $POSTGRES_PORT; do
               echo 'Waiting for database to be ready...';
               sleep 2;
             done &&
             echo 'Database is ready!' &&
             echo 'Running database migrations...' &&
             PGSSLMODE=disable npm run db:migrate &&
             npm start"
    restart: unless-stopped

volumes:
  uploads:

networks:
  host-your-gif-network:
    driver: bridge
