version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://urial:uQ6:qS5]oD0$hC1$@europe-west1-001.proxy.kinsta.app:30463/free-turquoise-wren
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_USER=urial
      - POSTGRES_PASSWORD=uQ6\:qS5\]oD0\$hC1\$
      - POSTGRES_DB=free-turquoise-wren
      - POSTGRES_HOST=europe-west1-001.proxy.kinsta.app
      - POSTGRES_PORT=30463
      - JWT_SECRET=3gVtqZpFtj8rew+PNefXJPtCdlNWm6lCXZykZmYCXR4=
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    command: >
      sh -c "npm run db:migrate && npm start"

volumes:
  uploads:

networks:
  host-your-gif-network:
    driver: bridge
