version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://urial@free-turquoise-wren-0v6xs-postgresql.free-turquoise-wren-0v6xs.svc.cluster.local:5432/free-turquoise-wren
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
